/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function int16ToFloat32(input: Int16Array): Promise<Float32Array>
export declare function float32ToInt16(input: Float32Array): Promise<Int16Array>
export declare function interleave(channels: Array<Float32Array>): Promise<Float32Array>
export declare function deinterleave(interleaved: Float32Array, numChannels: number): Promise<Array<Float32Array>>
export declare function magnitudeSpectrum(signal: Float32Array, fftSize: number): Promise<Float32Array>
export declare function powerSpectrumDb(signal: Float32Array, fftSize: number): Promise<Float32Array>
export declare function realFft(signal: Float32Array, fftSize: number): Promise<Float32Array>
export declare function realIfft(spectrum: Float32Array, fftSize: number): Promise<Float32Array>
export interface BiquadCoefficients {
  b0: number
  b1: number
  b2: number
  a1: number
  a2: number
}
/** Design biquad filter coefficients (synchronous). */
export declare function designBiquad(filterType: string, sampleRate: number, frequency: number, q?: number | undefined | null, gain?: number | undefined | null): BiquadCoefficients
export interface LevelResult {
  rms: number
  rmsDb: number
  peak: number
  peakDb: number
}
export declare function measureLevel(samples: Float32Array): Promise<LevelResult>
/** Resampler quality preset. */
export const enum ResamplerQuality {
  /** Sinc, sinc_len=256, cubic interpolation, BlackmanHarris2 */
  Best = 0,
  /** Sinc, sinc_len=128, cubic, Blackman2 */
  High = 1,
  /** Sinc, sinc_len=64, linear, Hann */
  Medium = 2,
  /** Polynomial cubic */
  Low = 3,
  /** Polynomial linear */
  Fastest = 4
}
/** One-shot resample (stateless, creates and destroys resampler internally). */
export declare function resample(input: Float32Array, inputRate: number, outputRate: number, channels?: number | undefined | null, quality?: ResamplerQuality | undefined | null): Promise<Float32Array>
export interface SpectrumResult {
  magnitudesBase64: string
  magnitudesLength: number
  scale: number
  offset: number
  peakFrequency: number
  peakMagnitude: number
  averageMagnitude: number
  dynamicRange: number
  frequencyResolution: number
  maxFrequency: number
}
/** Generate window function coefficients (synchronous, lightweight). */
export declare function createWindow(windowType: string, length: number): Float64Array
/** Apply a window function to a signal. */
export declare function applyWindow(signal: Float32Array, windowType: string): Promise<Float32Array>
export declare class BiquadFilter {
  constructor(coefficients: BiquadCoefficients)
  process(input: Float32Array): Promise<Float32Array>
  reset(): void
}
export declare class Resampler {
  constructor(inputRate: number, outputRate: number, channels?: number | undefined | null, quality?: ResamplerQuality | undefined | null)
  /** Stream processing (maintains filter state across calls). */
  process(input: Float32Array): Promise<Float32Array>
  /** Flush remaining samples from internal buffer. */
  flush(): Promise<Float32Array>
  /** Reset filter state. */
  reset(): void
  /** Output delay in frames. */
  get outputDelay(): number
  /** Release native resources. */
  dispose(): void
}
export declare class SpectrumAnalyzer {
  constructor(sampleRate: number, fftSize: number, windowFunction?: string | undefined | null, targetSampleRate?: number | undefined | null)
  analyze(audioData: Float32Array): Promise<SpectrumResult>
}
